"use client";

import React from 'react';
import { Sprout, TreeDeciduous, Flower2, Search, Info } from 'lucide-react';
import { motion } from 'framer-motion';

const KnowledgeGarden = ({ scannedObjects }: { scannedObjects: any[] }) => {
  // Sample data if none provided
  const gardenItems = scannedObjects.length > 0 ? scannedObjects : [
    { word: "Chair", story: "The silent observer of your hard work.", type: "sprout" },
    { word: "Laptop", story: "A portal to infinite digital wisdom.", type: "tree" },
    { word: "Coffee", story: "The fuel of late-night IELTS mastery.", type: "flower" }
  ];

  return (
    <div className="flex flex-col h-full p-8 bg-matcha-soft/20">
      <div className="flex items-center justify-between mb-8">
         <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm">
               <Sprout className="text-matcha-primary w-6 h-6" />
            </div>
            <div>
               <h2 className="text-xl font-black text-latte-brown">Object Story Garden</h2>
               <p className="text-[10px] font-bold text-matcha-primary uppercase tracking-widest">Your Knowledge Trees</p>
            </div>
         </div>
      </div>

      <div className="grid grid-cols-3 gap-6 flex-1 items-end pb-8">
         {gardenItems.slice(0, 3).map((item, i) => (
           <motion.div 
             key={i}
             initial={{ scale: 0, y: 20 }}
             animate={{ scale: 1, y: 0 }}
             transition={{ delay: i * 0.2 }}
             className="flex flex-col items-center group cursor-pointer"
           >
              <div className="relative mb-4">
                 {item.type === 'tree' ? (
                    <TreeDeciduous className="w-16 h-16 text-matcha-dark group-hover:scale-125 transition-transform duration-500" />
                 ) : item.type === 'flower' ? (
                    <Flower2 className="w-12 h-12 text-pink-400 group-hover:scale-125 transition-transform duration-500" />
                 ) : (
                    <Sprout className="w-10 h-10 text-matcha-primary group-hover:scale-125 transition-transform duration-500" />
                 )}
                 <div className="absolute -top-2 -right-2 bg-white w-6 h-6 rounded-full flex items-center justify-center shadow-md opacity-0 group-hover:opacity-100 transition-opacity">
                    <Search className="w-3 h-3 text-matcha-primary" />
                 </div>
              </div>
              <div className="sticker text-[9px] whitespace-nowrap shadow-sm group-hover:-translate-y-2 transition-transform">
                 {item.word.toUpperCase()}
              </div>
              
              {/* Tooltip-style Story */}
              <div className="absolute bottom-full mb-12 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none w-48 z-50">
                 <div className="bg-white p-4 rounded-2xl shadow-2xl border border-matcha-primary/20 text-[10px] font-bold text-latte-brown/80 leading-relaxed italic">
                    "{item.story}"
                 </div>
                 <div className="w-3 h-3 bg-white rotate-45 mx-auto -mt-1.5 border-r border-b border-matcha-primary/20" />
              </div>
           </motion.div>
         ))}
      </div>

      <div className="bg-white/60 p-4 rounded-3xl border border-white flex items-center gap-4">
         <div className="w-10 h-10 bg-cream-yellow rounded-xl flex items-center justify-center shrink-0">
            <Info className="text-latte-brown w-5 h-5" />
         </div>
         <p className="text-[10px] font-bold text-latte-brown/60 leading-tight">
            Knowledge Trees grow from scanned objects. Each tree holds a unique story generated by AI.
         </p>
      </div>
    </div>
  );
};

export default KnowledgeGarden;
